# branches to build
branches:
  # whitelist
  only:
    - master
    - appveyor_debug

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\stp

platform:
  - x64
#  - x86

environment:
  global:
    BOOST_ROOT: C:\projects\stp\boost_1_59_0_install
    MINISAT_ROOT: C:\projects\stp\minisat\myinstall
    ZLIB_ROOT: C:\projects\stp\zlib\myinstall
    BUILD_TYPE: Release
    MSBUILD_FLAGS: /maxcpucount /nologo

configuration:
  - Release

build_script:
  #- IF "%PLATFORM%" == "x86" ( SET BOOST_LIBRARYDIR=C:/Libraries/boost_1_59_0/lib32-msvc-14.0)
  - IF "%PLATFORM%" == "x86" ( SET CMAKE_GENERATOR="Visual Studio 14 2015")

  #- IF "%PLATFORM%" == "x64" ( SET BOOST_LIBRARYDIR=C:/Libraries/boost_1_59_0/lib64-msvc-14.0)
  - IF "%PLATFORM%" == "x64" ( SET CMAKE_GENERATOR="Visual Studio 14 2015 Win64")

  - echo %PLATFORM%
  - echo %BOOST_LIBRARYDIR%
  - echo %CMAKE_GENERATOR%
  - echo %configuration%
  - echo %APPVEYOR_BUILD_FOLDER%
  - echo %cd%

  # boost
  #- cd c:\projects\stp
  #- mkdir boost_1_59_0_install
  #- ps: . .\scripts\build\appveyor.ps1
  #- cd boost_1_59_0
  #- echo "Building boost.."
  #- bootstrap.bat --with-libraries=program_options
  #- cat project-config.jam
  #- b2 --with-program_options address-model=64 toolset=msvc-14.0 variant=release link=static threading=multi runtime-link=static install --prefix="C:\projects\stp\boost_1_59_0_install" > boost_install.out

  # zlib
  # TODO check out http://stackoverflow.com/questions/10507893/libzip-with-visual-studio-2010
  - cd C:\projects\stp
  - git clone https://github.com/madler/zlib
  - cd zlib
  - git checkout v1.2.8
  - echo %cd%
  - mkdir build
  - mkdir myinstall
  - cd build
  - cmake -G %CMAKE_GENERATOR% -DCMAKE_INSTALL_PREFIX=%ZLIB_ROOT% ..
  - if %PLATFORM%==x86 call msbuild %MSBUILD_FLAGS% /t:Build /p:Configuration=%CONFIGURATION% /p:Platform="x86" zlib.sln
  - if %PLATFORM%==x64 call msbuild %MSBUILD_FLAGS% /t:Build /p:Configuration=%CONFIGURATION% /p:Platform="x64" zlib.sln
  - msbuild %MSBUILD_FLAGS% INSTALL.vcxproj
  - dir ..\myinstall\

  # minisat
  - cd C:\projects\stp
  - git clone https://github.com/msoos/minisat
  - cd minisat
  - echo %cd%
  - mkdir build
  - mkdir myinstall
  - cd build
  - cmake -G %CMAKE_GENERATOR% -DCMAKE_INSTALL_PREFIX=%MINISAT_ROOT% -DZLIB_ROOT=%ZLIB_ROOT% ..
  - msbuild %MSBUILD_FLAGS% INSTALL.vcxproj
  - dir ..\myinstall\
  - dir ..\myinstall\lib\
  - dir ..\myinstall\bin\
  - dir ..\myinstall\include\

  # cygwin
  # - C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P autoconf -P automake -P bison -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl
  - C:\cygwin64\setup-x86_64.exe  -qnNd -R C:/cygwin64 --site http://cygwin.mirrors.pair.com/ -l C:/cygwin64/var/cache/setup --packages "flex,bison,perl,python"



  # finally STP
  - cd c:\projects\stp
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake --version
  - cmake -G %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DMINISAT_LIBDIR=%MINISAT_ROOT% -DMINISAT_INCLUDE_DIRS=%MINISAT_ROOT%\include -DCMAKE_PREFIX_PATH=C:\cygwin64 ..
  - msbuild %MSBUILD_FLAGS% INSTALL.vcxproj


build:
  # project: INSTALL.vcxproj      # path to Visual Studio solution or project
  parallel: true
  verbosity: minimal


# scripts to run after build
after_build:
  - 7z a c:\projects\stp\stp.zip %APPVEYOR_BUILD_FOLDER%\build -tzip
  - cd c:\projects\stp

artifacts:
  - path: stp.zip
    name: stp.zip

deploy_script:
  #- cd c:\projects\stp
  #- curl -T stp.zip --user %ACCOUNT% https://someplace/

test: off
